version: '3.7'
services:
  app:
    image: node:16.4.2-alpine
    container_name: payments_service
    working_dir: /usr/src/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_started
    ports:
      - '3333:3333'
    volumes:
      - .:/usr/src/app
    links:
      - db:db
    command: sh -c "./start.sh"
  db:
    image: postgres:latest
    container_name: db_payments
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -P password"]
      interval: 10s
      timeout: 5s
      retries: 5